name: code-check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  code-check:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install LLD
        run: sudo apt-get install lld -y
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
      - name: Install Rust
        run: rustup toolchain install stable --component llvm-tools
      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@v1.6.4
      - name: Install deps
        run: cargo binstall cargo-deny cargo-nextest cargo-watch sqlx-cli --no-confirm
      - uses: Swatinem/rust-cache@v2
      - name: Check code format
        run: cargo fmt -- --check
      - name: Check the package for errors
        run: cargo check --all
      - name: Lint rust sources
        run: cargo clippy --all-targets --all-features --tests --benches -- -D warnings
      - name: Load .env and start the database
        run: |
          set -a
          . ./.env
          set +a
          docker run -d --name postgres -e POSTGRES_USER=$POSTGRES_USER -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD -e POSTGRES_DB=$POSTGRES_DB -p 5432:5432 postgres:alpine
      - name: Execute rust tests
        run: |
          set -a
          . ./.env
          set +a
          cargo nextest run --all-features
      - name: Clean up Docker containers
        run: |
          docker stop postgres
          docker rm postgres
